1. Write a Python Program to find sum of array?

In [11]:
import numpy as np

a = np.array([1,5,6,8,9,4])
sum=0
for i in a:
  sum += i

print(sum)

33


2. Write a Python Program to find largest element in an array?

In [21]:
a = np.array([[1,5,6,8,9,4], [8,10,16,2,3,5]])
a.max()
print(a[1])

[ 8 10 16  2  3  5]


In [16]:
a.T

array([[ 1,  8],
       [ 5, 10],
       [ 6, 16],
       [ 8,  2],
       [ 9,  3],
       [ 4,  5]])

4. Write a Python Program to Split the array and add the first part to the end?

In [49]:
def split_array(arr, n, k):
  for i in range(0, k):
    first_val = arr[0]
    for j in range(0, n-1):
      arr[j] = arr[j + 1]
    arr[n-1] = first_val
  print(arr)
   
arr = np.array([1,5,6,8,9,4,8,10,16,2,3,5])
list_len = len(arr)
pos = 3
print("The list is :")
print(arr)
print("The split_list method is being called")
split_array(arr, list_len, pos)


The list is :
[ 1  5  6  8  9  4  8 10 16  2  3  5]
The split_list method is being called
[ 8  9  4  8 10 16  2  3  5  1  5  6]


5. Write a Python Program to check if given array is Monotonic?

In [53]:
a = np.array([1,2,3,5,6,8,9])
b = np.array([9,8,6,4,3,2,1])
c = np.array([1,2,3,6,5,8,9])

In [80]:
def check_mono(a):
  mono = False
  for i in range(1, len(a)-1):
    if a[0] > a[1] and a[i] >= a[i+1]:
      mono = True
    elif a[0] < a[1] and a[i] <= a[i+1]:
      mono = True
    else:
      mono = False
      break
  if mono == True:
    print("Array is monotonous")
  else:
    print("Array is not monotonous")

In [81]:
check_mono(a)

Array is monotonous


In [82]:
check_mono(b)

Array is monotonous


In [83]:
check_mono(c)

Array is not monotonous
