1. Create a function based on the input and output. Look at the examples,
there is a pattern.

Examples

secret(&quot;p.one.two.three&quot;) ➞ &quot;&lt;p class=&#39;one two three&#39;&gt;&lt;/p&gt;&quot;

secret(&quot;p.one&quot;) ➞ &quot;&lt;p class=&#39;one&#39;&gt;&lt;/p&gt;&quot;

secret(&quot;p.four.five&quot;) ➞ &quot;&lt;p class=&#39;four five&#39;&gt;&lt;/p&gt;&quot;

In [9]:
def secret(txt):
  a = txt.split(".")
  b = a.pop(0)
  class1 = " ".join(map(str, a))
  pattern = "<" + b + " class=" + "'{}'".format(class1) + "></" + b + ">"
  return pattern 

In [10]:
secret("p.four.five")

"<p class='four five'></p>"

3. Write a method that accepts two integer parameters rows and cols. The
output is a 2d array of numbers displayed in column-major order, meaning the
numbers shown increase sequentially down each column and wrap to the top
of the next column to the right once the bottom of the current column is
reached.

Examples

printGrid(3, 6) ➞ [
[1, 4, 7, 10, 13, 16],
[2, 5, 8, 11, 14, 17],
[3, 6, 9, 12, 15, 18]
]

printGrid(5, 3) ➞ [
[1, 6, 11],
[2, 7, 12],
[3, 8, 13],
[4, 9, 14],
[5, 10, 15]
]

In [30]:
def printGrid(a,b):
  lst1 = []
  for i in range(b):
    for j in range(a):
      if i == 0:
        lst1.append([(i+1)*(j+1)])
      else:
        lst1[j].append((i+1)*(j+1))
  return lst1

In [31]:
printGrid(5, 3)

[[1, 2, 3], [2, 4, 6], [3, 6, 9], [4, 8, 12], [5, 10, 15]]

In [32]:
printGrid(3, 6)

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [3, 6, 9, 12, 15, 18]]

In [40]:
import numpy as np
def printgrid(a,b):
  lst1 = [i for i in range(1, a*b+1)]
  arr = np.array(lst1)
  arr = np.reshape(arr, (b,a))
  return arr.T

In [41]:
printgrid(3,6)

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

In [42]:
printgrid(5,3)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [43]:
printgrid(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [46]:
lst1 = [[1,2],[3,[1,3]]]
arr = np.array(lst1)
arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([[1, 2],
       [3, list([1, 3])]], dtype=object)

5. Google is launching a network of autonomous pizza delivery drones and
wants you to create a flexible rewards system (Pizza Points™) that can be
tweaked in the future. The rules are simple: if a customer has made at least N
orders of at least Y price, they get a FREE pizza!
Create a function that takes a dictionary of customers, a minimum number of
orders and a minimum order price. Return a list of customers that are eligible
for a free pizza.

Examples

customers = {
&quot;Batman&quot;: [22, 30, 11, 17, 15, 52, 27, 12],
&quot;Spider-Man&quot;: [5, 17, 30, 33, 40, 22, 26, 10, 11, 45]
}

pizza_points(customers, 5, 20) ➞ [&quot;Spider-Man&quot;]

pizza_points(customers, 3, 10) ➞ [&quot;Batman&quot;, &quot;Spider-Man&quot;]

pizza_points(customers, 5, 100) ➞ []

In [48]:
customers = { "Batman": [22, 30, 11, 17, 15, 52, 27, 12], 
             "Spider-Man": [5, 17, 30, 33, 40, 22, 26, 10, 11, 45], 
             "Hit-Man": [35, 27, 30, 53, 10, 22, 6, 57, 101, 95] 
             }

In [59]:
def pizza_points(dict1, orders, prize):
  lst1 = []
  count = 0
  for i in dict1.items():
    for j in i[1]:
      if j >= prize:
        count += 1
    if count >= orders:
      lst1.append(i[0])
  return lst1

In [60]:
pizza_points(customers, 3, 10)

['Batman', 'Spider-Man', 'Hit-Man']

In [62]:
pizza_points(customers, 2, 90)

['Hit-Man']